### ISSUE TITLE
Installing a version of Wine other than 5.0

### ISSUE THREAD

**Issue by yllekz** [Gcenx/wine-on-mac#3]
Hello, pardon me if this is a stupid question, but when I install Wine on macOS using this repository's instructions, it installs an old version of Wine. How can I specify to install the latest version instead?

**Comment by Gcenx** [comment]
As explained in the README 

https://github.com/Gcenx/wine-on-mac/blob/1761a7e3370e856ce9fb8fb208505348247ab520/README.md#L25-L36

Doing this will allow installing the most recent wine packages I provide this will only function on macOS High Sierra and later.

If you require wine for OS X 10.8 to macOS 10.12 you’ll need to compile from source using my Macports overlay.

**Comment by yllekz** [comment]
Beautiful, that worked. Before I was only running one of those components (wine-crossover) which explains why it wasn't grabbing the latest. Thanks!
