### ISSUE TITLE
Latest wine-stable package via-Homebrew doesn't work on macOS 10.14

### ISSUE THREAD

**Issue by palikao** [Gcenx/wine-on-mac#6]
Latest wine-stable package via-Homebrew doesn't work on macOS 10.14.. It requires 10.15, and it's absurd!

Keep availability

**Comment by Gcenx** [comment]
I no longer own a working Intel Mac, let alone one that can run macOS Mojave.

Please keep in mind that Mojave released September 24 2018, even CodeWeavers have officially dropped support. Supporting macOS Catalina is way less completed then trying to support macOS Mojave that requires i386 & x86_64 dylibs.
