### ISSUE TITLE
Might need some updates in README

### ISSUE THREAD

**Issue by jamesellinger** [Gcenx/wine-on-mac#7]
This page is a great resource for Apple users who want to get wine up and running.  But I think a few points need updating.

1. wine-staging is now wine@staging (might be the same for wine-devel, but I didn't check).
2. 

> Apple Silicon support?
Only CrossOver-20.0.2 includes 32Bit support for Apple Silicon at this time, this requires macOS Big Sur 11.1 and Rosetta2 installed.
Wine-6.0.1/Wine-6.1 only support 64Bit Windows Binaries at this time.

32Bit binaries will run on Apple Silicon running wine 9.x (at least for me 32Bit binaries have worked from 9.5 to 9.8)

**Comment by Gcenx** [comment]
I’m surprised anyone reads this, I’ve slightly updated it to more reflect the current Winehq packages installed via brew as I’m also the maintainer.

**Comment by jamesellinger** [comment]
Thanks! Over the past couple of years I've become a heavy user of wine on a mac. Not sure how I found this site in the first place, but it's been very helpful.
